# Generated by Django 4.2.13 on 2024-08-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='en', max_length=2),
        ),
    ]
