# Generated by Django 4.2.13 on 2024-06-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_subscriptionoption_delete_durationoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.FileField(upload_to='car_images/'),
        ),
    ]
