# Generated by Django 4.2.13 on 2024-05-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_carservice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelservice',
            name='day_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
