# Generated by Django 4.2.13 on 2024-06-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_carimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoption',
            name='type',
            field=models.CharField(choices=[('Extras', 'Extras'), ('Scent Service', 'Scent Service'), ('Beverages', 'Beverages'), ('Snacks', 'Snacks')], max_length=100),
        ),
    ]
