# Generated by Django 4.2.13 on 2024-06-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_serviceoption_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelservice',
            name='address',
            field=models.CharField(blank=True, default='Cairo', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='location_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='location_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
