# Generated by Django 4.2.13 on 2024-06-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_hotelservice_address_hotelservice_location_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoption',
            name='sub_type',
        ),
    ]
