# Generated by Django 4.2.13 on 2024-06-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_serviceoption_sub_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='HotelServiceFeatures',
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='features',
            field=models.ManyToManyField(related_name='hotel_services', to='services.hotelservicefeature'),
        ),
    ]
