# Generated by Django 4.2.13 on 2024-06-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_hotelservicefeature_delete_hotelservicefeatures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carservice',
            name='make',
        ),
        migrations.RemoveField(
            model_name='carservice',
            name='model',
        ),
    ]
