# Generated by Django 4.2.13 on 2024-06-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_carmake_carmodel_carservice_make_carservice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelservice',
            name='availability_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='availability_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
