# Generated by Django 4.2.13 on 2024-06-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_hotelservice_availability_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='make',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='name',
            field=models.CharField(default='model', max_length=100, unique=True),
        ),
    ]
