# Generated by Django 4.2.13 on 2024-06-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_carmodel_make_carmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmake',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='carmake',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='name_ar',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotelservice',
            name='name_en',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
