# Generated by Django 4.2.13 on 2024-06-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_carmake_name_ar_carmake_name_en_hotelservice_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservice',
            name='features',
            field=models.ManyToManyField(to='services.hotelservicefeature'),
        ),
    ]
