# Generated by Django 4.2.13 on 2024-06-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_carmodel_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelservice',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionoption',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
