# Generated by Django 4.2.13 on 2024-07-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_hotelimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_image/'),
        ),
    ]
