# Generated by Django 4.2.13 on 2024-07-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_hotelservice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelservice',
            name='points_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='points_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subscriptionoption',
            name='points_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelservice',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionoption',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
