# Generated by Django 4.2.13 on 2024-07-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_hotelservice_points_price_serviceoption_points_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservice',
            name='points_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='points_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionoption',
            name='points_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
