# Generated by Django 4.2.13 on 2024-08-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_hotelservice_dollar_day_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='belong_to_parent',
            field=models.BooleanField(default=False),
        ),
    ]
