# Generated by Django 4.2.13 on 2024-08-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_hotelimage_belong_to_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='belong_to_parent',
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='is_3d',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='level',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
