# Generated by Django 4.2.13 on 2024-05-29 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='hotelreservationoption',
            name='hotel_reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='reservations.hotelreservation'),
        ),
        migrations.AddField(
            model_name='hotelreservationoption',
            name='service_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reservation_options', to='services.serviceoption'),
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='hotel_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reservations', to='services.hotelservice'),
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reservations', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='carreservationoption',
            name='car_reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='reservations.carreservation'),
        ),
        migrations.AddField(
            model_name='carreservationoption',
            name='service_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_reservation_options', to='services.serviceoption'),
        ),
        migrations.AddField(
            model_name='carreservation',
            name='car_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_reservations', to='services.carservice'),
        ),
        migrations.AddField(
            model_name='carreservation',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_reservations', to='reservations.reservation'),
        ),
    ]
