# Generated by Django 4.2.13 on 2024-06-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_carreservation_final_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelreservation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hotelreservation',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='hotelreservation',
            name='location_long',
        ),
        migrations.RemoveField(
            model_name='hotelreservation',
            name='location_url',
        ),
    ]
