# Generated by Django 4.2.13 on 2024-07-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_reservation_status_delete_refund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
