# Generated by Django 4.2.13 on 2024-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms of Use'), ('cancellation', 'Cancellation Policy')], max_length=20, unique=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
