# Generated by Django 4.2.13 on 2024-06-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
