# Generated by Django 4.2.13 on 2024-08-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='content_en',
            field=models.TextField(null=True),
        ),
    ]
