# Generated by Django 4.2.13 on 2024-08-09 12:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_policy_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='content_ar',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
